export const THEMES = [
  {
    id: 'modern-saas',
    name: 'Modern SaaS',
    description: 'Clean, professional SaaS-style with gradient accents and cards',
    preview: { bg: '#0f0f1a', accent: '#6366f1', text: '#f1f5f9', card: '#1e1e2e' },
    tags: ['Dark', 'Professional', 'Popular'],
    isPremium: false,
  },
  {
    id: 'developer-terminal',
    name: 'Developer Terminal',
    description: 'Hacker aesthetic with terminal green, monospace fonts, and CLI feel',
    preview: { bg: '#0d1117', accent: '#00ff41', text: '#c9d1d9', card: '#161b22' },
    tags: ['Dark', 'Hacker', 'Unique'],
    isPremium: false,
  },
  {
    id: 'creative-designer',
    name: 'Creative Designer',
    description: 'Bold typography, vibrant colors, asymmetric layouts for creatives',
    preview: { bg: '#fafafa', accent: '#ff3366', text: '#111111', card: '#ffffff' },
    tags: ['Light', 'Creative', 'Bold'],
    isPremium: false,
  },
  {
    id: 'minimal-professional',
    name: 'Minimal Professional',
    description: 'Ultra-clean whitespace, serif typography, sophisticated and timeless',
    preview: { bg: '#ffffff', accent: '#1a1a2e', text: '#222222', card: '#f8f8f8' },
    tags: ['Light', 'Minimal', 'Clean'],
    isPremium: false,
  },
  {
    id: 'futuristic-ai',
    name: 'Futuristic AI',
    description: 'Cyberpunk neon on dark canvas with glowing borders and sci-fi vibes',
    preview: { bg: '#050510', accent: '#00d4ff', text: '#e0e0ff', card: '#0a0a20' },
    tags: ['Dark', 'Neon', 'Sci-Fi'],
    isPremium: false,
  },
  {
    id: 'startup-founder',
    name: 'Startup Founder',
    description: 'Orange energy, bold sections, and startup pitch-deck aesthetics',
    preview: { bg: '#0a0a0a', accent: '#ff6b00', text: '#ffffff', card: '#141414' },
    tags: ['Dark', 'Energetic', 'Bold'],
    isPremium: false,
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Frosted glass cards, blur effects, and aurora gradient backgrounds',
    preview: { bg: '#0d0820', accent: '#a855f7', text: '#f0e6ff', card: 'rgba(255,255,255,0.08)' },
    tags: ['Dark', 'Glass', 'Modern'],
    isPremium: false,
  },
  {
    id: 'premium-dark',
    name: 'Premium Dark',
    description: 'Luxury gold accents, rich dark surfaces, and editorial typography',
    preview: { bg: '#0a0800', accent: '#d4af37', text: '#f5f0e8', card: '#111008' },
    tags: ['Dark', 'Luxury', 'Gold'],
    isPremium: true,
  },
  // ── Premium themes — Pro plan required to select ──────────────────────
  {
    id: 'executive-suite',
    name: 'Executive Suite',
    description: 'Navy and gold corporate layout with a commanding hero and refined data presentation — built for C-suite and consulting portfolios',
    preview: { bg: '#0a0e1a', accent: '#c9a227', text: '#e8e6df', card: '#0d1326' },
    tags: ['Dark', 'Corporate', 'Pro'],
    isPremium: true,
  },
  {
    id: 'neon-cyber-pro',
    name: 'Neon Cyber Pro',
    description: 'Animated particle field, holographic cards, and layered glow effects — the most elaborate cyberpunk layout in the catalog',
    preview: { bg: '#060109', accent: '#ff2bd6', text: '#f0e6fa', card: '#1a0a22' },
    tags: ['Dark', 'Animated', 'Pro'],
    isPremium: true,
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial Magazine',
    description: 'Print-magazine layout with a masthead header, drop-cap intro, and feature-article styling for experience and projects',
    preview: { bg: '#f7f3ea', accent: '#a3271f', text: '#1a1a1a', card: '#fffdf8' },
    tags: ['Light', 'Editorial', 'Pro'],
    isPremium: true,
  },
  {
    id: 'architect-blueprint',
    name: 'Architect Blueprint',
    description: 'Technical drafting aesthetic with blueprint grid lines, corner brackets, and dimension-line styling for a precise, engineered feel',
    preview: { bg: '#0c2d4a', accent: '#5ec8e8', text: '#cfe8f5', card: 'rgba(255,255,255,0.02)' },
    tags: ['Dark', 'Technical', 'Pro'],
    isPremium: true,
  },
  {
    id: 'velvet-noir',
    name: 'Velvet Noir',
    description: 'Cinematic, moody dark layout with dramatic italic type, spotlight gradients, and a film-credits-inspired experience section',
    preview: { bg: '#0a0608', accent: '#8a1538', text: '#ece4e6', card: '#151012' },
    tags: ['Dark', 'Cinematic', 'Pro'],
    isPremium: true,
  },
];

export const getTheme = (id) => THEMES.find(t => t.id === id) || THEMES[0];
